import type { Metadata, Viewport } from "next";
import { Chivo, JetBrains_Mono, Sora } from "next/font/google";

import "./globals.css";

import { Header } from "@/components/layout/Header";
import { Footer } from "@/components/layout/Footer";
import { JsonLd } from "@/components/seo/JsonLd";
import { themeScript } from "@/components/layout/ThemeToggle";
import { graph, organizationSchema, personSchema, websiteSchema } from "@/lib/schema-org";
import { site, siteUrl } from "@/lib/site";

/* Type — Duvaryne identity system.
   Sora for display (the wordmark is Sora Light), Chivo for body, JetBrains Mono for
   every quantity and utility label. Sora and Chivo preload; the mono face does not,
   because it is below the fold on most pages. `display: swap` keeps text painting
   immediately, which matters because every LCP element on this site is text. */
const sora = Sora({
  subsets: ["latin"],
  weight: ["200", "300", "400"],
  variable: "--font-sora",
  display: "swap",
  preload: true,
});

const chivo = Chivo({
  subsets: ["latin"],
  weight: ["300", "400", "600"],
  variable: "--font-chivo",
  display: "swap",
  preload: true,
});

const jetbrains = JetBrains_Mono({
  subsets: ["latin"],
  weight: ["400", "500"],
  variable: "--font-jetbrains",
  display: "swap",
  preload: false,
});

/**
 * Search-console ownership tokens.
 *
 * Read from the environment rather than committed: they are per-property, they change
 * when a property is re-verified, and a token for someone else's property in the repo is
 * just confusing. Absent values are omitted from the head entirely — Next drops undefined
 * keys, so an unset variable produces no empty meta tag.
 */
const verification = {
  google: process.env.NEXT_PUBLIC_GOOGLE_SITE_VERIFICATION,
  other: {
    ...(process.env.NEXT_PUBLIC_BING_SITE_VERIFICATION
      ? { "msvalidate.01": process.env.NEXT_PUBLIC_BING_SITE_VERIFICATION }
      : {}),
  },
};

export const metadata: Metadata = {
  // siteUrl() normalises and validates. Passing the raw env var here fails the entire
  // build with a bare "TypeError: Invalid URL" if anyone types the host without a scheme.
  metadataBase: new URL(siteUrl()),
  title: {
    default: "AWS & DevOps Consulting in Bengaluru | Duvaryne",
    template: `%s`,
  },
  description: "Senior-led AWS and DevOps consulting from Bengaluru. Migration, Kubernetes, CI/CD and cost optimisation delivered by the engineer who reviews your account.",
  applicationName: site.name,
  authors: [{ name: site.founder.name, url: site.social.linkedin }],
  creator: site.founder.name,
  publisher: site.name,
  formatDetection: { telephone: false, address: false, email: false },
  /* Google has ignored the keywords meta since 2009 and it is not here to influence
     ranking. It is carried because Bing, Yandex and several AI answer engines still read
     it as a weak topical hint, and because the cost is one line. Ranking comes from the
     copy, the schema and the links — not from this. */
  keywords: [
    "AWS consulting",
    "DevOps consulting",
    "AWS consulting Bengaluru",
    "DevOps services India",
    "Kubernetes consulting",
    "AWS cost optimisation",
    "cloud migration",
    "CI/CD",
    "Terraform",
    "site reliability engineering",
    site.shortName,
    site.name,
  ],
  category: "technology",
  // The canonical is set per page by buildMetadata; only the feed is global.
  alternates: {
    types: { "application/rss+xml": [{ url: "/rss.xml", title: `${site.shortName} blog` }] },
  },
  verification,
  // Icons are generated by app/icon.tsx and app/apple-icon.tsx; Next wires them up
  // automatically, so declaring paths here would only risk pointing at files that
  // do not exist.
};

export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
  /* Platinum ground in light, ink in dark. Neither is black — the identity forbids it,
     and the browser chrome is as much the brand as the page is. */
  /* The site ships dark for everyone, so the browser chrome matches the ground
     rather than the visitor's OS preference. */
  themeColor: "#23282D",
  colorScheme: "dark light",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html
      lang="en-IN"
      className={`${sora.variable} ${chivo.variable} ${jetbrains.variable}`}
      /* The pre-paint script sets data-theme before React sees the document, so the
         server and client markup legitimately differ on this attribute. */
      suppressHydrationWarning
    >
      <head>
        {/* Must run synchronously, before first paint. Deferring it means every visitor
            with a stored preference sees a flash of the wrong palette. */}
        <script dangerouslySetInnerHTML={{ __html: themeScript }} />
      </head>
      <body className="flex min-h-screen flex-col">
        {/* Skip link — SPEC §11.2. First focusable element on every page. */}
        <a
          href="#main"
          className="sr-only focus:not-sr-only focus:absolute focus:left-4 focus:top-4 focus:z-[100] focus:bg-inverse-deep focus:px-4 focus:py-3 focus:text-on-inverse"
        >
          Skip to content
        </a>

        <Header />
        <main id="main" className="flex-1">
          {children}
        </main>
        <Footer />

        <JsonLd json={graph(organizationSchema(), websiteSchema(), personSchema())} />

        {/* Cookieless — no consent banner required for these alone. SPEC §12.6. */}
      </body>
    </html>
  );
}
