import type { Metadata, Viewport } from "next";
import { Archivo, IBM_Plex_Mono, IBM_Plex_Sans } from "next/font/google";

import "./globals.css";

import { Header } from "@/components/layout/Header";
import { Footer } from "@/components/layout/Footer";
import { JsonLd } from "@/components/seo/JsonLd";
import { graph, organizationSchema, personSchema, websiteSchema } from "@/lib/schema-org";
import { site, siteUrl } from "@/lib/site";

/* Fonts — SPEC §6.2. Archivo and Plex Sans preload; Plex Mono does not, because it is
   below the fold on most pages. `display: swap` keeps text painting immediately, which
   matters because every LCP element on this site is text. */
const archivo = Archivo({
  subsets: ["latin"],
  variable: "--font-archivo",
  display: "swap",
  preload: true,
});

const plexSans = IBM_Plex_Sans({
  subsets: ["latin"],
  weight: ["400", "500", "600"],
  variable: "--font-plex-sans",
  display: "swap",
  preload: true,
});

const plexMono = IBM_Plex_Mono({
  subsets: ["latin"],
  weight: ["400", "500"],
  variable: "--font-plex-mono",
  display: "swap",
  preload: false,
});

export const metadata: Metadata = {
  // siteUrl() normalises and validates. Passing the raw env var here fails the entire
  // build with a bare "TypeError: Invalid URL" if anyone types the host without a scheme.
  metadataBase: new URL(siteUrl()),
  title: {
    default: "AWS & DevOps Consulting in Bengaluru | Duvaryne",
    template: `%s`,
  },
  description:
    "Senior-led AWS and DevOps consulting from Bengaluru. Migration, Kubernetes, CI/CD and cost optimisation delivered by the engineer who reviews your account.",
  applicationName: site.name,
  authors: [{ name: site.founder.name, url: site.social.linkedin }],
  creator: site.founder.name,
  publisher: site.name,
  formatDetection: { telephone: false, address: false, email: false },
  // Icons are generated by app/icon.tsx and app/apple-icon.tsx; Next wires them up
  // automatically, so declaring paths here would only risk pointing at files that
  // do not exist.
};

export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
  themeColor: "#11243E",
  colorScheme: "light",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html
      lang="en-IN"
      className={`${archivo.variable} ${plexSans.variable} ${plexMono.variable}`}
    >
      <body className="flex min-h-screen flex-col">
        {/* Skip link — SPEC §11.2. First focusable element on every page. */}
        <a
          href="#main"
          className="sr-only focus:not-sr-only focus:absolute focus:left-4 focus:top-4 focus:z-[100] focus:rounded-md focus:bg-navy-900 focus:px-4 focus:py-3 focus:text-white"
        >
          Skip to content
        </a>

        <Header />
        <main id="main" className="flex-1">
          {children}
        </main>
        <Footer />

        <JsonLd json={graph(organizationSchema(), websiteSchema(), personSchema())} />

        {/* Cookieless — no consent banner required for these alone. SPEC §12.6. */}
      </body>
    </html>
  );
}
