import type { MetadataRoute } from "next";
import { site } from "@/lib/site";

/**
 * Web app manifest.
 *
 * Not a PWA — there is no service worker and no offline story, and adding one to a
 * marketing site would be ceremony. The manifest is here for the mundane reasons: it
 * gives Android's "add to home screen" a real name and colour instead of a screenshot of
 * the favicon, and it is one of the places a crawler looks for the site's short name.
 *
 * `display: "browser"` is deliberate. "standalone" would strip the URL bar from a site
 * whose whole job is to be linked, shared and read.
 */
export default function manifest(): MetadataRoute.Manifest {
  return {
    name: site.name,
    short_name: site.shortName,
    description:
      "Senior-led AWS and DevOps consulting from Bengaluru. Migration, Kubernetes, CI/CD and cost optimisation.",
    start_url: "/",
    display: "browser",
    lang: "en-IN",
    // Matches the `themeColor` in the root layout's viewport export. The site ships dark
    // for everyone, so both are the ink ground rather than the light platinum.
    background_color: "#23282D",
    theme_color: "#23282D",
    categories: ["business", "productivity"],
    icons: [
      // Generated by app/icon.tsx and app/apple-icon.tsx. Sizes here must match what
      // those routes actually render, or Android silently rejects the entry.
      { src: "/icon", sizes: "32x32", type: "image/png" },
      { src: "/apple-icon", sizes: "180x180", type: "image/png" },
    ],
  };
}
